name: schoolcalculator_flutter
description: SchoolCalculator Flutter version

publish_to: 'none'

version: 0.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  numberpicker: ^2.1.1
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  fl_chart: ^0.36.3
  carousel_slider: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - imgs/

  fonts:
    - family: SCDream
      fonts:
        - asset: fonts/csdream1.otf
          weight: 100
        - asset: fonts/scdream2.otf
          weight: 200
        - asset: fonts/scdream3.otf
          weight: 300
        - asset: fonts/scdream4.otf
          weight: 400
        - asset: fonts/scdream5.otf
          weight: 500
        - asset: fonts/scdream6.otf
          weight: 600
        - asset: fonts/scdream7.otf
          weight: 700
        - asset: fonts/scdream8.otf
          weight: 800
        - asset: fonts/scdream9.otf
          weight: 900